alias: Heating - Schedule - Morning climates pre-heat (weekdays & weekends)
description: ""
mode: single
triggers:
  - at: "06:40:00"
    trigger: time
conditions:
  - condition: state
    entity_id: input_boolean.heating_automation
    state: "on"
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
actions:
  - metadata: {}
    data:
      hvac_mode: heat
      temperature: 18.5
    target:
      entity_id:
        - climate.YOUR_CLIMATE_NAME
        - climate.YOUR_CLIMATE_NAME_2
        - climate.YOUR_CLIMATE_NAME_3
        - ...
    action: climate.set_temperature
